export const ADMIN_LIST_UPDATE = 'ac/ADMIN_LIST_UPDATE'
export const ADMIN_PAGINATION_UPDATE = 'ac/ADMIN_PAGINATION_UPDATE'
export const CHURCH_ALL_LIST_UPDATE = 'ac/CHURCH_ALL_LIST_UPDATE'
export const CHURCH_MAPPING_LIST_UPDATE = 'ac/CHURCH_MAPPING_LIST_UPDATE'