

export const CHILDREN_LIST_UPDATE = 'chac/CHILDREN_LIST_UPDATE'
export const CHURCH_PAGINATION_UPDATE = 'chac/CHURCH_PAGINATION_UPDATE'
export const CHILDREN_PAGINATION_UPDATE = 'chac/CHILDREN_PAGINATION_UPDATE'