export const CHURCH_SELECTED_UPDATE ='aa/CHURCH_SELECTED_UPDATE'
export const AVAILABLE_CHURCH_UPDATE ='aa/AVAILABLE_CHURCH_UPDATE'
export const CURRENT_TOKEN_UPDATE ='aa/CURRENT_TOKEN_UPDATE'
export const CURRENT_ROLE_UPDATE ='aa/CURRENT_ROLE_UPDATE'